//
//  CurrencyModel.swift
//  Money Manager
//
//  Created by Oleh Falalieiev on 04.12.2021.
//

import Foundation

struct CurrencyModel {
    
    var currencyArray = ["(AED) United Arab Emirates dirham - د.إ",
                          "(AFN) Afghan afghani - ؋",
                          "(ALL) Albanian lek - L",
                          "(AMD) Armenian dram - դր",
                          "(ANG) Netherlands Antillean guilder - ƒ",
                          "(AOA) Angolan kwanza - Kz",
                          "(ARS) Argentine peso - $",
                          "(AUD) Australian dollar - $",
                          "(AWG) Aruban florin - ƒ",
                          "(AZN) Azerbaijani manat - m",
                          "(BAM) Bosnia and Herzegovina convertible mark - КМ",
                          "(BBD) Barbados dollar - $",
                          "(BDT) Bangladeshi taka - ৳",
                          "(BGN) Bulgarian lev - лв",
                          "(BHD) Bahraini dinar - .د.ب",
                          "(BIF) Burundian franc - Fr",
                          "(BMD) Bermudian dollar - $",
                          "(BND) Brunei dollar - $",
                          "(BOB) Boliviano - Bs",
                          "(BRL) Brazilian real - R$",
                          "(BSD) Bahamian dollar - $",
                          "(BTN) Bhutanese ngultrum - Nu",
                          "(BWP) Botswana pula - P",
                          "(BYR) Belarusian ruble - Br",
                          "(BZD) Belize dollar - $",
                          "(CAD) Canadian dollar - $",
                          "(CDF) Congolese franc - Fr",
                          "(CHF) Swiss franc - Fr",
                          "(CLP) Chilean peso - $",
                          "(CNY) Chinese yuan - ¥",
                          "(COP) Colombian peso - $",
                          "(CRC) Costa Rican colon - ₡",
                          "(CUC) Cuban convertible peso - $",
                          "(CUP) Cuban peso - $",
                          "(CVE) Cape Verde escudo - $",
                          "(CZK) Czech koruna - Kč",
                          "(DJF) Djiboutian franc - Fr",
                          "(DKK) Danish krone - kr",
                          "(DOP) Dominican peso - $",
                          "(DZD) Algerian dinar - د.ج",
                          "(EGP) Egyptian pound - ج.م",
                          "(ERN) Eritrean nakfa - ናቕፋ",
                          "(ETB) Ethiopian birr - Br",
                          "(EUR) Euro - €",
                          "(FJD) Fiji dollar - $",
                          "(FKP) Falkland Islands pound - £",
                          "(GBP) Pound sterling - £",
                          "(GEL) Georgian lari - ლ",
                          "(GHS) Ghanaian cedi - ₵",
                          "(GIP) Gibraltar pound - £",
                          "(GMD) Gambian dalasi - D",
                          "(GNF) Guinean franc - Fr",
                          "(GTQ) Guatemalan quetzal - Q",
                          "(GYD) Guyanese dollar - $",
                          "(HKD) Hong Kong dollar - $",
                          "(HNL) Honduran lempira - L",
                          "(HRK) Croatian kuna - kn",
                          "(HTG) Haitian gourde - G",
                          "(HUF) Hungarian forint - Ft",
                          "(IDR) Indonesian rupiah - Rp",
                          "(ILS) Israeli new shekel - ₪",
                          "(INR) Indian rupee - ₹",
                          "(IQD) Iraqi dinar - ع.د",
                          "(IRR) Iranian rial - ﷼",
                          "(ISK) Icelandic króna - kr",
                          "(JMD) Jamaican dollar - $",
                          "(JOD) Jordanian dinar - د.ا",
                          "(JPY) Japanese yen - ¥",
                          "(KES) Kenyan shilling - Sh",
                          "(KGS) Kyrgyzstani som - лв",
                          "(KHR) Cambodian riel - ៛",
                          "(KMF) Comoro franc - Fr",
                          "(KPW) North Korean won - ₩",
                          "(KRW) South Korean won - ₩",
                          "(KWD) Kuwaiti dinar - د.ك",
                          "(KYD) Cayman Islands dollar - $",
                          "(KZT) Kazakhstani tenge - ₸",
                          "(LAK) Lao kip - ₭",
                          "(LBP) Lebanese pound - ل.ل",
                          "(LKR) Sri Lankan rupee - Rs",
                          "(LRD) Liberian dollar - $",
                          "(LSL) Lesotho loti - L",
                          "(LTL) Lithuanian litas - Lt",
                          "(LYD) Libyan dinar - ل.د",
                          "(MAD) Moroccan dirham - د.م.",
                          "(MDL) Moldovan leu - L",
                          "(MGA) Malagasy ariary - Ar",
                          "(MKD) Macedonian denar - ден",
                          "(MMK) Myanma kyat - Ks",
                          "(MNT) Mongolian tugrik - ₮",
                          "(MOP) Macanese pataca - P",
                          "(MRO) Mauritanian ouguiya - UM",
                          "(MUR) Mauritian rupee - ₨",
                          "(MVR) Maldivian rufiyaa - .ރ",
                          "(MWK) Malawian kwacha - MK",
                          "(MXN) Mexican peso - $",
                          "(MYR) Malaysian ringgit - RM",
                          "(MZN) Mozambican metical - MT",
                          "(NAD) Namibian dollar - $",
                          "(NGN) Nigerian naira - ₦",
                          "(NIO) Nicaraguan córdoba - C$",
                          "(NOK) Norwegian krone - kr",
                          "(NPR) Nepalese rupee - ₨",
                          "(NZD) New Zealand dollar - $",
                          "(OMR) Omani rial - ر.ع.",
                          "(PAB) Panamanian balboa - B/",
                          "(PEN) Peruvian nuevo sol - S/",
                          "(PGK) Papua New Guinean kina - K",
                          "(PHP) Philippine peso - ₱",
                          "(PKR) Pakistani rupee - ₨",
                          "(PLN) Polish złoty - zł",
                          "(PYG) Paraguayan guaraní - ₲",
                          "(QAR) Qatari riyal - ر.ق",
                          "(RON) Romanian new leu - L",
                          "(RSD) Serbian dinar - дин",
                          "(RUB) Russian rouble - ₽",
                          "(RWF) Rwandan franc - Fr",
                          "(SAR) Saudi riyal - ر.س",
                          "(SBD) Solomon Islands dollar - $",
                          "(SCR) Seychelles rupee - ₨",
                          "(SDG) Sudanese pound - £",
                          "(SEK) Swedish krona - kr",
                          "(SGD) Singapore dollar - $",
                          "(SHP) Saint Helena pound - £",
                          "(SLL) Sierra leonean leone - Le",
                          "(SOS) Somali shilling - Sh",
                          "(SRD) Surinamese dollar - $",
                          "(SSP) South Sudanese pound - £",
                          "(STD) São Tomé and Príncipe dobra - Db",
                          "(SYP) Syrian pound - ل.س",
                          "(SZL) Swazi lilangeni - L",
                          "(THB) Thai baht - ฿",
                          "(TJS) Tajikistani somoni - ЅМ",
                          "(TMT) Turkmenistani manat - m",
                          "(TND) Tunisian dinar - د.ت",
                          "(TOP) Tongan paʻanga - T$",
                          "(TRY) Turkish lira - ₺",
                          "(TTD) Trinidad and Tobago dollar - $",
                          "(TWD) New Taiwan dollar - $",
                          "(TZS) Tanzanian shilling - Sh",
                          "(UAH) Ukrainian hryvnia - ₴",
                          "(UGX) Ugandan shilling - Sh",
                          "(USD) United States dollar - $",
                          "(UYU) Uruguayan peso - $",
                          "(UZS) Uzbekistan som - лв",
                          "(VEF) Venezuelan bolívar fuerte - Bs F",
                          "(VND) Vietnamese dong - ₫",
                          "(VUV) Vanuatu vatu - Vt",
                          "(WST) Samoan tala - T",
                          "(XAF) CFA franc BEAC - Fr",
                          "(XCD) East Caribbean dollar - $",
                          "(XOF) CFA franc BCEAO - Fr",
                          "(XPF) CFP franc - Fr",
                          "(YER) Yemeni rial - ﷼",
                          "(ZAR) South African rand - R",
                          "(ZMW) Zambian kwacha - ZK"]
}
